name: hello-world
on: 
  schedule:
    - cron: '*/5 * * * *'
jobs:
  kristina-job:
    runs-on: ubuntu-latest
    steps:
      - name: kristina-step
        run: echo "Kristina 5 minutes Hello World!"
